package me.albamhp.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.albamhp.VideoManager;
import me.albamhp.gui.components.PlayButton;
import me.albamhp.gui.components.Splitter;
import me.albamhp.gui.components.StopButton;
import me.albamhp.gui.components.TimeLine;
import me.albamhp.gui.components.VideoPlayer;
import me.albamhp.gui.components.WheelDisplayer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class GUI extends JFrame {
    private TimeLine timeSlider;
    private JPanel rootPanel;
    private VideoPlayer videoPlayer;
    private WheelDisplayer wheelDisplayer;
    private PlayButton playB;
    private StopButton stopB;

    public VideoManager manager;

    public GUI() {
        super("File Viewer");

        setContentPane(rootPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        manager = new VideoManager(videoPlayer, timeSlider, playB, stopB, wheelDisplayer);

        setSize(500, 500);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setMinimumSize(new Dimension(-1, -1));
        rootPanel.setOpaque(true);
        rootPanel.setPreferredSize(new Dimension(-1, -1));
        rootPanel.setRequestFocusEnabled(true);
        rootPanel.putClientProperty("html.disable", Boolean.FALSE);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 5, 5, 5), 0, 0));
        rootPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        playB = new PlayButton();
        playB.setHorizontalAlignment(0);
        playB.setText("");
        panel1.add(playB, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        timeSlider = new TimeLine();
        timeSlider.setExtent(0);
        timeSlider.setInverted(false);
        timeSlider.setMaximum(-1);
        timeSlider.setMinorTickSpacing(0);
        timeSlider.setPaintLabels(false);
        timeSlider.setPaintTicks(false);
        timeSlider.setValue(-1);
        timeSlider.setValueIsAdjusting(false);
        panel1.add(timeSlider, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1, false));
        stopB = new StopButton();
        stopB.setHorizontalAlignment(0);
        panel1.add(stopB, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Splitter splitter1 = new Splitter();
        splitter1.setDividerLocation(471);
        splitter1.setDividerSize(5);
        splitter1.setForeground(new Color(-16777216));
        splitter1.setOneTouchExpandable(false);
        splitter1.setResizeWeight(0.5);
        rootPanel.add(splitter1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        splitter1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        videoPlayer = new VideoPlayer();
        splitter1.setLeftComponent(videoPlayer);
        wheelDisplayer = new WheelDisplayer();
        splitter1.setRightComponent(wheelDisplayer);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
